title: Build a coldsmoker
hero_image: images/banner.jpg
description: Add delicious flavours and create new dishes
theme: blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: 
interests:
technologies:
site_areas: hackspace
steps:
  - title: Introduction
  - title: What you will need
  - title: Firebox
  - title: Selecting wood
  - title: Ducting
  - title: Smoke chamber
  - title: Delicious food
