---
title: Build a cold smoker
hero_image: images/banner.jpg
description: Add delicious flavours and create new dishes
theme: blue
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: 
technologies: 
site_areas: HackSpace
steps:
- title: Introduction
- title: What you will need
- title: Firebox
- title: Selecting wood
- title: Ducting
- title: Smoke chamber
- title: Delicious food
